language: python
python:
  - "2.7"
before_install:
  - bash .travis.install-mysql-5.7.sh
  - pip install -r requirements.txt
install:
  - sudo mysql -uroot -e "GRANT ALL PRIVILEGES ON * . * TO 'root'@'localhost';"
  - sudo mysql -uroot -e "CREATE DATABASE IF NOT EXISTS twitch"
  - sudo mysql -uroot twitch < schema.sql
  - cp src/config/config_example.py src/config/config.py
  - cp globals_example.py globals.py
  - cd /home/travis/build/singlerider/lorenzotherobot/
  - pwd
script: ls
# whitelist
sudo: true
